name: Publish to GitHub Packages Registry

# Version: 2.0.1
# Modified: No
# Requirements:
# - The `name` in `package.json` should start with `@athombv/`.
#
# Secrets:
# - HOMEY_GITHUB_ACTIONS_BOT_PERSONAL_ACCESS_TOKEN
#
# Ensure you've run `npm version major|minor|patch` on the `master` branch before merging to `production`.
#
# This GitHub Workflow:
# 1. [Optional] If `npm run build` exists. If so, it runs `npm ci` and `npm run build`.
# 2. Publishes the package to the GitHub Packages Registry.

on:
  push:
    branches:
      - production

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:

      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Set up node 16 environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          
      - name: Build
        run: |
          if jq --exit-status '.scripts | has("build")' package.json; then
            echo "'npm run build' does exist. Building..."
            npm ci
            npm run build
          else
            echo "'npm run build' does not exist. Skipping build..."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.HOMEY_GITHUB_ACTIONS_BOT_PERSONAL_ACCESS_TOKEN }}

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
